version: '3.9'

services:
  interface:
    build: ./interface/
    ports:
      - "5002:5002"
    command: "python3 interface.py"
  
  app:
    build: ./app/
    depends_on:
      - mysql
      - redis
    ports:
      - "5001:5001"
    command: sh -c "sleep 15s ; python3 app.py"
  mysql:
    build: ./database/
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'newuser'
      MYSQL_ROOT_PASSWORD: 'userpassword'
  redis:
    image: "redis:alpine"
    command: "redis-server"
    ports:
      - "6379:6379"
