server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: trace
  
positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: flask_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: "flask_app"
          __path__: /var/log/flask_app.log
